"""The generated reference pages match the code (OSS plan R7).

``docs/reference/cli.md`` and ``docs/reference/environment-variables.md`` are written by
``scripts/gen_reference_docs.py`` from the stable CLI and the settings catalog. This
runs the script's ``--check``: a new option, a changed help string or a new setting
fails here until the pages are regenerated. The script runs in a child process because
it pins its own environment (a throwaway IRIS_HOME, the ``email`` profile) before the
CLI is imported.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SCRIPT = ROOT / "scripts" / "gen_reference_docs.py"


def test_the_reference_pages_are_current() -> None:
    done = subprocess.run(  # noqa: S603 -- this repository's own script
        [sys.executable, str(SCRIPT), "--check"],
        cwd=ROOT,
        env=dict(os.environ),
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )
    assert done.returncode == 0, done.stderr or done.stdout


def test_the_pages_are_marked_generated() -> None:
    for name in ("cli.md", "environment-variables.md"):
        text = (ROOT / "docs" / "reference" / name).read_text(encoding="utf-8")
        assert text.startswith("<!-- Generated by scripts/gen_reference_docs.py"), name


def test_the_settings_page_lists_the_stable_settings_first_and_collapses_the_rest() -> None:
    from iris_harness.testing import stable_tier

    stable = stable_tier().settings
    assert stable, "stable_tier.yaml declares the stable settings"
    assert len(set(stable)) == len(stable)
    text = (ROOT / "docs" / "reference" / "environment-variables.md").read_text(encoding="utf-8")
    head, appendix = text.split("## Every other setting", 1)
    stable_section = head.split("## Stable settings", 1)[1]
    listed = re.findall(r"^\| `(IRIS_[A-Z0-9_]+)` \|", stable_section, re.MULTILINE)
    assert tuple(listed) == stable
    # The full catalog sits in a collapsed (`???`) admonition marked not stable, and
    # lists each stable setting again, marked so.
    assert appendix.lstrip().startswith('??? note "') and "(not stable)" in appendix
    for name in stable:
        row = rf"^    \| `{name}` \|.*\*\*Stable\.\*\* \|$"
        assert re.search(row, appendix, re.MULTILINE), name
