"""Generate the docs site's reference pages from the code (OSS plan R7).

Two pages, both written from what the install itself declares, never by hand:

* ``docs/reference/cli.md`` -- the stable CLI: exactly the commands
  ``src/iris_harness/sdk/stable_tier.yaml`` lists under ``quickstart_cli``, read from the
  ``iris`` Typer app (help text, usage, every option with its type and default).
* ``docs/reference/environment-variables.md`` -- the stable settings first (the ones
  ``stable_tier.yaml`` lists under ``settings``), then, in a collapsed appendix marked
  not stable, every ``IRIS_*`` setting the settings catalog declares for the ``email``
  profile: the core catalog (``src/iris_harness/foundation/settings/catalog.yaml``) plus
  each plugin the profile mounts (its manifest's ``settings:``).

Usage:
    python scripts/gen_reference_docs.py            # (re)write both pages
    python scripts/gen_reference_docs.py --check    # exit 1 when a page is stale

``tests/unit/test_docs/test_reference_docs.py`` runs ``--check``, so a new option, a
changed help string or a new setting fails the suite until the pages are regenerated.

The pages must not depend on the machine that renders them, so the script runs the CLI
with a pinned environment: a throwaway ``IRIS_HOME`` (no personal plugins, no profile
overlay) and ``IRIS_PROFILE=email`` (the profile release 1 ships, whose plugins add the
``iris email`` commands). It loads this tree's ``src/`` first, so a checkout renders its
own code, not whatever an installed copy holds.
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CLI_PAGE = ROOT / "docs" / "reference" / "cli.md"
ENV_PAGE = ROOT / "docs" / "reference" / "environment-variables.md"
PROFILE = "email"

_GENERATED = (
    "<!-- Generated by scripts/gen_reference_docs.py; do not edit by hand. "
    "Run `python scripts/gen_reference_docs.py` after changing {what}. -->"
)


def _pin_environment(home: Path) -> None:
    """Before anything from ``iris_harness`` is imported: the profile and a clean home."""
    for name in list(os.environ):
        if name.startswith("IRIS_"):
            del os.environ[name]
    os.environ["IRIS_HOME"] = str(home)
    os.environ["IRIS_PROFILE"] = PROFILE
    os.environ["IRIS_DISABLE_WARMUP"] = "1"
    sys.path.insert(0, str(ROOT / "src"))


def _cell(text: str) -> str:
    """One markdown table cell: a single line, pipes escaped."""
    return " ".join(text.split()).replace("|", "\\|")


# ── the CLI page ────────────────────────────────────────────────────────────────────


def _option_row(param: Any) -> str:
    names = ", ".join(f"`{o}`" for o in [*param.opts, *param.secondary_opts])
    if getattr(param, "is_flag", False):
        kind = "flag"
        default = ""
    else:
        kind = str(param.type.name).upper()
        default = "" if param.default in (None, "", ()) else f"`{param.default}`"
    return f"| {names} | {kind} | {default} | {_cell(param.help or '')} |"


def render_cli() -> str:
    import click
    import typer

    from iris_harness.main import app
    from iris_harness.testing import stable_tier

    root = typer.main.get_command(app)
    lines = [
        _GENERATED.format(what="a stable command's options or help"),
        "",
        "# CLI reference",
        "",
        "The stable commands: the ones `src/iris_harness/sdk/stable_tier.yaml` lists. They",
        "change only after a deprecation cycle ([Stable API](stable-api.md)). `iris --help`",
        "lists every other command; those are internal and may change in any release.",
        "",
    ]
    for path in stable_tier().quickstart_cli:
        ctx = click.Context(root, info_name="iris")
        cmd: Any = root
        for part in path:
            cmd = cmd.get_command(ctx, part)
            if cmd is None:
                raise SystemExit(
                    f"stable_tier.yaml lists `iris {' '.join(path)}`, which the CLI lacks "
                    f"(profile {PROFILE!r})"
                )
            ctx = click.Context(cmd, info_name=part, parent=ctx)
        name = "iris " + " ".join(path)
        usage = " ".join([name, *cmd.collect_usage_pieces(ctx)])
        lines += [f"## `{name}`", ""]
        lines += [(cmd.help or "").strip(), ""]
        lines += ["```text", usage, "```", ""]
        options = [p for p in cmd.params if isinstance(p, click.Option)]
        arguments = [p for p in cmd.params if isinstance(p, click.Argument)]
        if arguments:
            lines += ["| Argument | Type | Required |", "|---|---|---|"]
            for arg in arguments:
                lines.append(
                    f"| `{arg.name.upper()}` | {str(arg.type.name).upper()} | "
                    f"{'yes' if arg.required else 'no'} |"
                )
            lines.append("")
        lines += ["| Option | Type | Default | Description |", "|---|---|---|---|"]
        lines += [_option_row(p) for p in options]
        lines += ["| `--help` | flag |  | Show the command's help and exit. |", ""]
    return "\n".join(lines).rstrip() + "\n"


# ── the settings page ───────────────────────────────────────────────────────────────


def _profile_catalog() -> Any:
    from iris_harness.foundation.paths import config_path
    from iris_harness.foundation.settings.catalog import build_catalog, load_core_catalog
    from iris_harness.runtime.plugin_host.loader import discover_plugin
    from iris_harness.runtime.plugin_host.profile import load_profile

    config_dir = config_path("profiles").parent
    declared = []
    for ref in load_profile(config_dir, PROFILE).plugins:
        source = discover_plugin(ref.name)
        if source is None:
            raise SystemExit(f"profile {PROFILE!r} lists plugin {ref.name!r}, not found")
        declared.append((f"plugin:{source.manifest.name}", dict(source.manifest.settings)))
    return build_catalog(load_core_catalog(), declared)


def _default(value: Any) -> str:
    if value is None or value == "":
        return ""
    if isinstance(value, bool):
        return "`on`" if value else "`off`"
    if isinstance(value, list):
        return "`" + ",".join(str(v) for v in value) + "`" if value else ""
    return f"`{value}`"


_APPLIES = {"now": "next call", "next_run": "next run", "restart": "restart"}

# Not `IRIS_*`, so outside the settings catalog's scope (`catalog.py` rejects any
# other prefix) -- the two local-model backends' own address variables, read
# straight from the environment wherever the harness talks to them
# (`llm/tier_router.py`, the health checks' service probes). Documented here by
# hand, inside the generated page, so they do not silently stay undiscoverable.
_THIRD_PARTY_SETTINGS: tuple[tuple[str, str, str], ...] = (
    (
        "OLLAMA_BASE_URL",
        "`http://localhost:11434`",
        "Ollama's base URL (a trailing `/v1` is accepted and trimmed). Set it to move the "
        "local-model backend to another box -- the cloud harness reaches the Mac's Ollama "
        "over the tailnet this way.",
    ),
    (
        "LM_STUDIO_BASE_URL",
        "`http://localhost:1234`",
        "LM Studio's base URL, shared with the LLM failover proxy -- told apart by port "
        "(the proxy's `IRIS_PROXY_PORT`, default 4000, vs. LM Studio's 1234).",
    ),
)


_HEADER = "| Variable | Kind | Default | Applies | Description |"
_RULE = "|---|---|---|---|---|"


def _row(entry: Any) -> str:
    d = entry.declaration
    guarded = " **Guarded.**" if d.guarded else ""
    return (
        f"| `{entry.name}` | {d.kind} | {_cell(_default(d.default))} | "
        f"{_APPLIES[d.applies]} | {_cell(d.description)}{guarded} |"
    )


def _owner_title(owner: str) -> str:
    return "core" if owner == "core" else f"plugin `{owner.split(':', 1)[1]}`"


def render_env() -> str:
    from iris_harness.testing import stable_tier

    catalog = _profile_catalog()
    stable = stable_tier().settings
    missing = [name for name in stable if name not in catalog.entries]
    if missing:
        raise SystemExit(
            "stable_tier.yaml lists settings the email profile's catalog does not declare: "
            + ", ".join(missing)
        )
    owners: dict[str, list[Any]] = {}
    for entry in catalog.entries.values():
        owners.setdefault(entry.owner, []).append(entry)
    lines = [
        _GENERATED.format(
            what="a settings catalog, a plugin manifest's `settings:` or the "
            "stable settings in `src/iris_harness/sdk/stable_tier.yaml`"
        ),
        "",
        "# Environment variables",
        "",
        "Set them in the environment or in a `.env` file the CLI and the IRIS API read at",
        "start.",
        "",
        "- **Applies**: when a change takes effect (the next call, the next scheduled run,",
        "  or a restart).",
        "- **Guarded**: the web console asks the owner to confirm a change.",
        "- On/off settings take `1`/`true`/`yes`/`on` and `0`/`false`/`no`/`off`.",
        "",
        "## Stable settings",
        "",
        "What an install of `iris-harness[email]` needs: the settings the getting-started",
        "pages, the email guide and `iris doctor` name. They are part of the",
        "[stable API](stable-api.md): a name or a default changes only after a deprecation",
        "cycle. `src/iris_harness/sdk/stable_tier.yaml` lists them.",
        "",
        _HEADER,
        _RULE,
    ]
    lines += [_row(catalog.entries[name]) for name in stable]
    lines += [
        "",
        "## Third-party model backends",
        "",
        "Not `IRIS_*`, so outside the settings catalog's scope -- the local-model",
        "backends' own address variables, read wherever the harness talks to them.",
        "",
        "| Variable | Default | Description |",
        "|---|---|---|",
    ]
    lines += [
        f"| `{name}` | {default} | {_cell(desc)} |" for name, default, desc in _THIRD_PARTY_SETTINGS
    ]
    lines += [
        "",
        "## Every other setting",
        "",
        '??? note "The full catalog of the `email` profile (not stable)"',
        "",
        "    Every `IRIS_*` setting the install reads, from the settings catalog: the",
        "    core's (`src/iris_harness/foundation/settings/catalog.yaml`) and each plugin's",
        f"    in the `{PROFILE}` profile (its manifest's `settings:`). A test fails when the",
        "    code reads an `IRIS_*` name no catalog declares. The stable settings above are",
        "    listed again here, marked **Stable**.",
        "",
        "    These are configuration, **not** part of the stable API: a name or a default",
        "    may change in a 0.x release, and the release notes say so.",
        "",
    ]
    order = ["core"] + sorted(o for o in owners if o != "core")
    for owner in order:
        lines += [f"    **From {_owner_title(owner)}**", "", f"    {_HEADER}", f"    {_RULE}"]
        for entry in owners[owner]:
            row = _row(entry)
            if entry.name in stable:
                row = row[: -len(" |")] + " **Stable.** |"
            lines.append(f"    {row}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ── main ────────────────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when a page is stale")
    args = parser.parse_args(argv)
    with tempfile.TemporaryDirectory(prefix="iris-refdocs-") as home:
        _pin_environment(Path(home))
        pages = {CLI_PAGE: render_cli(), ENV_PAGE: render_env()}
    stale = []
    for path, text in pages.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == text:
            continue
        if args.check:
            stale.append(path.relative_to(ROOT))
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print(
            "stale reference pages (run `python scripts/gen_reference_docs.py`): "
            + ", ".join(str(p) for p in stale),
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
