#!/usr/bin/env python3
"""Refresh the vendored ICANN public-suffix list (issue #175).

The egress declaration refuses a wildcard over a public suffix (``*.co.uk``): it would let a
plugin reach every registrant under that suffix. The suffixes come from Mozilla's Public Suffix
List, ICANN section only (the PRIVATE section lists hosting providers such as ``github.io``,
whose subdomains a plugin may legitimately declare), vendored as
``src/iris_harness/kernel/governance/public_suffix_icann.dat``.

    python scripts/refresh_public_suffixes.py             # fetch publicsuffix.org, rewrite
    python scripts/refresh_public_suffixes.py --from FILE # use a downloaded copy
    python scripts/refresh_public_suffixes.py --check     # exit 1 if the vendored file is stale

The list is licensed under MPL-2.0 (https://mozilla.org/MPL/2.0/); the vendored file keeps the
notice, its version and its source commit in its header, and that is the attribution. Rules are
written one per line, internationalised labels converted to their ``xn--`` form (the egress
host grammar is ASCII only). Refresh it when a new TLD or suffix appears; a stale list fails
closed only for suffixes created since.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

URL = "https://publicsuffix.org/list/public_suffix_list.dat"
TARGET = (
    Path(__file__).resolve().parents[1]
    / "src/iris_harness/kernel/governance/public_suffix_icann.dat"
)
_BEGIN = "// ===BEGIN ICANN DOMAINS==="
_END = "// ===END ICANN DOMAINS==="


def _ascii_label(label: str) -> str:
    if label == "*" or label.isascii():
        return label.lower()
    return label.encode("idna").decode("ascii").lower()


def convert(source: str) -> str:
    lines = source.splitlines()
    version = next((ln[3:].strip() for ln in lines if ln.startswith("// VERSION:")), "unknown")
    commit = next((ln[3:].strip() for ln in lines if ln.startswith("// COMMIT:")), "unknown")
    begin, end = lines.index(_BEGIN), lines.index(_END)
    rules: list[str] = []
    for raw in lines[begin + 1 : end]:
        rule = raw.split()[0] if raw.strip() and not raw.lstrip().startswith("//") else ""
        if not rule:
            continue
        bang = rule.startswith("!")
        body = rule[1:] if bang else rule
        try:
            ascii_rule = ".".join(_ascii_label(label) for label in body.split("."))
        except UnicodeError:
            continue
        if not re.fullmatch(r"(\*|[a-z0-9-]+)(\.[a-z0-9-]+)*", ascii_rule):
            continue
        rules.append(("!" if bang else "") + ascii_rule)
    header = (
        "// Mozilla Public Suffix List, ICANN section only. Vendored under the MPL-2.0:\n"
        "// This Source Code Form is subject to the terms of the Mozilla Public\n"
        "// License, v. 2.0. If a copy of the MPL was not distributed with this\n"
        "// file, You can obtain one at https://mozilla.org/MPL/2.0/.\n"
        f"// Source: {URL}\n"
        f"// {version}\n"
        f"// {commit}\n"
        "// Generated by scripts/refresh_public_suffixes.py: one rule per line, labels in\n"
        "// their xn-- form. `*.x` matches any label under x; `!x.y` is an exception.\n"
    )
    return header + "\n".join(sorted(set(rules))) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--from", dest="source", type=Path, help="read this file, do not fetch")
    parser.add_argument("--check", action="store_true", help="exit 1 if the vendored file differs")
    args = parser.parse_args()
    if args.source is not None:
        text = args.source.read_text(encoding="utf-8")
    else:
        with urllib.request.urlopen(URL, timeout=60) as reply:
            text = reply.read().decode("utf-8")
    out = convert(text)
    if args.check:
        return 0 if TARGET.read_text(encoding="utf-8") == out else 1
    TARGET.write_text(out, encoding="utf-8")
    print(f"wrote {TARGET} ({out.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
