"""Agent identity and self-knowledge layer.

Holds the four-layer agentic memory model (identity, long-term, episodic, active)
as user-editable markdown files at ``~/.iris/``. The runtime reads these at
session start and injects them into the system prompt.
"""

from .loader import (
    HARNESS_DOC_PATH,
    ActiveItem,
    Behavior,
    EpisodicPattern,
    active_md_path,
    add_active_item,
    agents_md_path,
    append_episodic_pattern,
    append_user_fact_to_md,
    behaviors_dir,
    bootstrap_identity_files,
    curated_fact_keys,
    drop_user_fact_from_md,
    episodic_md_path,
    iris_home,
    list_active_items,
    list_behaviors,
    list_episodic_patterns,
    load_active_md,
    load_agent_name,
    load_agents_md,
    load_curated_profile,
    load_episodic_digest,
    load_episodic_md,
    load_harness_md,
    load_soul,
    load_soul_core,
    load_soul_extended,
    load_user_md,
    mark_active_done,
    match_behavior,
    other_matching_behaviors,
    read_auto_fact_keys,
    reconcile_user_facts_md,
    score_behaviors,
    sync_user_facts_to_md,
    write_behavior,
    write_curated_profile,
)

__all__ = [
    "ActiveItem",
    "Behavior",
    "EpisodicPattern",
    "HARNESS_DOC_PATH",
    "active_md_path",
    "add_active_item",
    "agents_md_path",
    "append_episodic_pattern",
    "append_user_fact_to_md",
    "behaviors_dir",
    "bootstrap_identity_files",
    "curated_fact_keys",
    "drop_user_fact_from_md",
    "episodic_md_path",
    "iris_home",
    "list_active_items",
    "list_behaviors",
    "list_episodic_patterns",
    "load_active_md",
    "load_agent_name",
    "load_agents_md",
    "load_episodic_digest",
    "load_episodic_md",
    "load_harness_md",
    "load_curated_profile",
    "load_soul",
    "load_soul_core",
    "load_soul_extended",
    "load_user_md",
    "mark_active_done",
    "match_behavior",
    "other_matching_behaviors",
    "score_behaviors",
    "read_auto_fact_keys",
    "reconcile_user_facts_md",
    "sync_user_facts_to_md",
    "write_behavior",
    "write_curated_profile",
]
